import type { Property } from '@/types'

export const demoProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Villa with Infinity Pool',
    titleAr: 'فيلا حديثة مع مسبح لا متناهي',
    description: 'Stunning 5-bedroom villa with panoramic city views, private pool, and smart home automation.',
    descriptionAr: 'فيلا رائعة من 5 غرف نوم مع إطلالات بانورامية على المدينة ومسبح خاص وتشغيل آلي للمنزل.',
    price: 4500000,
    currency: 'SAR',
    location: 'Riyadh, Al Olaya District',
    locationAr: 'الرياض، حي العليا',
    lat: 24.6877,
    lng: 46.6517,
    area: 550,
    bedrooms: 5,
    bathrooms: 6,
    images: ['/images/prop-1.jpg'],
    type: 'sale',
    status: 'available',
    featured: true,
    createdAt: '2026-06-15',
    updatedAt: '2026-07-01',
  },
  {
    id: '2',
    title: 'Luxury Beachfront Apartment',
    titleAr: 'شقة فاخرة على الشاطئ',
    description: 'Elegant 3-bedroom apartment with direct beach access, sea view balcony, and premium finishes.',
    descriptionAr: 'شقة أنيقة من 3 غرف نوم مع وصول مباشر للشاطئ وشرفة بإطلالة بحرية وتشطيبات راقية.',
    price: 1200000,
    currency: 'SAR',
    location: 'Jeddah, Al Hamra District',
    locationAr: 'جدة، حي الحمراء',
    lat: 21.5433,
    lng: 39.1728,
    area: 220,
    bedrooms: 3,
    bathrooms: 3,
    images: ['/images/prop-2.jpg'],
    type: 'sale',
    status: 'available',
    featured: true,
    createdAt: '2026-06-20',
    updatedAt: '2026-07-05',
  },
  {
    id: '3',
    title: 'Executive Office Tower',
    titleAr: 'برج مكاتب تنفيذي',
    description: 'Prime commercial space in business bay, fully fitted with modern infrastructure.',
    descriptionAr: 'مساحة تجارية مميزة في الخليج التجاري مجهزة بالكامل ببنية تحتية حديثة.',
    price: 8000000,
    currency: 'SAR',
    location: 'Riyadh, King Abdullah Financial District',
    locationAr: 'الرياض، حي الملك عبد الله المالي',
    lat: 24.7606,
    lng: 46.6455,
    area: 1200,
    bedrooms: 0,
    bathrooms: 4,
    images: ['/images/prop-3.jpg'],
    type: 'sale',
    status: 'available',
    featured: true,
    createdAt: '2026-05-10',
    updatedAt: '2026-06-28',
  },
  {
    id: '4',
    title: 'Elegant Villa with Garden',
    titleAr: 'فيلا أنيقة مع حديقة',
    description: 'Spacious 4-bedroom villa with lush garden, majlis, and private parking for 4 cars.',
    descriptionAr: 'فيلا واسعة من 4 غرف نوم مع حديقة غناء ومجلس وموقف خاص لأربع سيارات.',
    price: 2800000,
    currency: 'SAR',
    location: 'Riyadh, Al Narjis District',
    locationAr: 'الرياض، حي النرجس',
    lat: 24.8142,
    lng: 46.6526,
    area: 400,
    bedrooms: 4,
    bathrooms: 5,
    images: ['/images/prop-4.jpg'],
    type: 'sale',
    status: 'available',
    featured: false,
    createdAt: '2026-07-01',
    updatedAt: '2026-07-08',
  },
  {
    id: '5',
    title: 'Modern Studio Apartment',
    titleAr: 'استوديو حديث',
    description: 'Fully furnished studio in the heart of the city, ideal for young professionals.',
    descriptionAr: 'استوديو مفروش بالكامل في قلب المدينة، مثالي للمحترفين الشباب.',
    price: 45000,
    currency: 'SAR',
    location: 'Dubai, Downtown',
    locationAr: 'دبي، وسط المدينة',
    lat: 25.2048,
    lng: 55.2708,
    area: 65,
    bedrooms: 1,
    bathrooms: 1,
    images: ['/images/prop-5.jpg'],
    type: 'rent',
    status: 'available',
    featured: false,
    createdAt: '2026-07-05',
    updatedAt: '2026-07-10',
  },
  {
    id: '6',
    title: 'Family Home with Pool',
    titleAr: 'منزل عائلي مع مسبح',
    description: 'Beautiful 5-bedroom home with large backyard, pool, and children\'s play area.',
    descriptionAr: 'منزل جميل من 5 غرف نوم مع فناء خلفي كبير ومسبح ومنطقة لعب للأطفال.',
    price: 180000,
    currency: 'SAR',
    location: 'Jeddah, Al Safa District',
    locationAr: 'جدة، حي الصفا',
    lat: 21.5656,
    lng: 39.1754,
    area: 350,
    bedrooms: 5,
    bathrooms: 4,
    images: ['/images/prop-6.jpg'],
    type: 'rent',
    status: 'available',
    featured: false,
    createdAt: '2026-06-25',
    updatedAt: '2026-07-08',
  },
  {
    id: '7',
    title: 'Penthouse with Skyline View',
    titleAr: 'بنتهاوس مع إطلالة الأفق',
    description: 'Ultra-luxury penthouse on the 45th floor with 360° city views and private terrace.',
    descriptionAr: 'بنتهاوس فاخر جداً في الطابق 45 مع إطلالة 360 درجة على المدينة وتراس خاص.',
    price: 9500000,
    currency: 'SAR',
    location: 'Riyadh, Al Aqiq District',
    locationAr: 'الرياض، حي العقيق',
    lat: 24.7249,
    lng: 46.6368,
    area: 350,
    bedrooms: 4,
    bathrooms: 5,
    images: ['/images/prop-7.jpg'],
    type: 'sale',
    status: 'available',
    featured: true,
    createdAt: '2026-06-01',
    updatedAt: '2026-07-12',
  },
  {
    id: '8',
    title: 'Commercial Retail Space',
    titleAr: 'مساحة تجزئة تجارية',
    description: 'High-footfall retail space in popular mall, ready for immediate operation.',
    descriptionAr: 'مساحة تجزئة عالية الحركة في مول شهير، جاهزة للتشغيل الفوري.',
    price: 3200000,
    currency: 'SAR',
    location: 'Jeddah, Al Rawdah District',
    locationAr: 'جدة، حي الروضة',
    lat: 21.5581,
    lng: 39.1915,
    area: 180,
    bedrooms: 0,
    bathrooms: 2,
    images: ['/images/prop-8.jpg'],
    type: 'sale',
    status: 'available',
    featured: false,
    createdAt: '2026-06-10',
    updatedAt: '2026-07-02',
  },
]

export const cities = [
  { value: 'all', label: 'All Cities', labelAr: 'جميع المدن' },
  { value: 'riyadh', label: 'Riyadh', labelAr: 'الرياض' },
  { value: 'jeddah', label: 'Jeddah', labelAr: 'جدة' },
  { value: 'dubai', label: 'Dubai', labelAr: 'دبي' },
]

export const propertyTypes = [
  { value: 'all', label: 'All Types', labelAr: 'جميع الأنواع' },
  { value: 'villa', label: 'Villa', labelAr: 'فيلا' },
  { value: 'apartment', label: 'Apartment', labelAr: 'شقة' },
  { value: 'commercial', label: 'Commercial', labelAr: 'تجاري' },
  { value: 'penthouse', label: 'Penthouse', labelAr: 'بنتهاوس' },
]

export const roomOptions = [
  { value: '0', label: 'Any', labelAr: 'أي' },
  { value: '1', label: '1+', labelAr: '1+' },
  { value: '2', label: '2+', labelAr: '2+' },
  { value: '3', label: '3+', labelAr: '3+' },
  { value: '4', label: '4+', labelAr: '4+' },
  { value: '5', label: '5+', labelAr: '5+' },
]

export const priceRanges = [
  { value: 'all', label: 'Any Price', labelAr: 'أي سعر' },
  { value: '0-500k', label: 'Under 500K', labelAr: 'أقل من 500 ألف' },
  { value: '500k-2m', label: '500K – 2M', labelAr: '500 ألف – 2 مليون' },
  { value: '2m-5m', label: '2M – 5M', labelAr: '2 – 5 مليون' },
  { value: '5m+', label: '5M+', labelAr: '5 مليون+' },
]
